global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#george_besedin'
