version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGODB}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - prometheus_net
      - front_net

  post:
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - prometheus_net
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
  prometheus_net:
